apiVersion: v1
kind: Service
metadata:
  name: go-con-manager
  labels:
    app: go-con-manager
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30021 # its important. UI app access this instance by knowing this node port
      name: client
  selector:
    app: go-con-manager